### ISSUE TITLE
条件如何产生，Action的返回值如何对状态转移产生影响？

### ISSUE THREAD

**Issue by JesseGuoX** [smallnest/gofsm#4]
您好，在看关于转门的例子时候有个疑问，如果从Lock到Unlock的触发条件是Coin，对应的动作是check，那如何对check的结果进行判断。比如我投币投了一个游戏币，那必然需要对check的返回进行检查，如果check返回成功才会把结果变成Unlock，如果check返回失败应该状态不变还是Lock才对。这种如何通过状态机实现呢？

**Comment by smallnest** [comment]
我更新了一下代码，增加了Action执行结果的校验。

如果执行某个action失败(比如游戏币值不足)， 状态冰不会迁移，而是返回一个错误
